language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mstrlarge/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mstrlarge/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env-alt"
  bucket_name: "elasticbeanstalk-us-west-2-351068244429"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
